### ISSUE TITLE
error

### ISSUE THREAD

**Issue by torskyy** [GDColon/GD-Randomizer#2]
i got a error (replaced my name with user haha)
Something went wrong! Send this error to Colon and he'll get around to fixing it at some point.

Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash/GJ_GameSheetGlow-uhd.plist'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.readFileSync (C:\Users\user\Downloads\Geometry dash randomizer\shuffle.exe:201:55)
    at Object.<anonymous> (C:\Users\user\Downloads\Geometry dash randomizer\shuffle.js:41:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

**Comment by GDColon** [comment]
GJ_GameSheetGlow-uhd.plist is missing
