### ISSUE TITLE
Issue Where if Geometry Dash Is Installed In Another Drive Then The Program Cant Find Where Geometry Dash Is, And Crashes With A Error

### ISSUE THREAD

**Issue by RealMamitler** [GDColon/GD-Randomizer#6]
Error Here: Error: ENOENT: no such file or directory, open 'C:/Program Files (x86)/Steam/steamapps/common/Geometry Dash/Resources/GJ_GameSheetGlow-uhd.plist'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.readFileSync (E:\the hole of downloads\GDRandomizer\shuffle.exe:201:55)
    at Object.<anonymous> (E:\the hole of downloads\GDRandomizer\shuffle.js:41:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
This probably be fixed.

**Comment by GDColon** [comment]
Change the directory in directory.txt or make sure GJGameSheetGlow exists
